### ISSUE TITLE
Adding R xThreat Implementation

### ISSUE THREAD

**Issue by gkrhines** [devinpleuler/analytics-handbook#13]
First of all, let me say how awesome this project is. As someone who has just begun getting interested in soccer analytics, it has been my go to when I have a new idea or do not understand something foreign to me. 

That being said, I am much more comfortable with R instead of Python. The lack of the former language in this handbook did make it hard to get started working with some of the tools that are provided. In the end, I actually ended up converting xthreat.py (from the socceraction repo) to an R script. That file can be found [here](https://github.com/gkrhines/xThreatR/blob/main/xThreat%20Applied.R).

If you wanted to add the script (which is SPADL compatible) to your handbook, I would be honored. I think it would allow programmers who have less experience with Python to be able to wrap their heads around the ideas they find here a little quicker.

Thanks for all your work!

**Comment by devinpleuler** [comment]
Thanks, Grant. I am going to keep this repository purely python – as that is the focus.

**Comment by gkrhines** [comment]
I understand! Thanks, Devin.
