### ISSUE TITLE
Another Open Dataset

### ISSUE THREAD

**Issue by bgrnwd** [devinpleuler/analytics-handbook#5]
Here's another dataset worth considering:

[Open Football](https://github.com/openfootball/leagues)

Pseudo event data

**Comment by devinpleuler** [comment]
Awesome. How frequently is this maintained?

**Comment by bgrnwd** [comment]
According to their [website](https://openfootball.github.io/index.html), there's no set schedule

> Q: What’s the update frequency of the datasets?
> 
>  A: It’s an open source (public domain) volunteer effort. Datasets get updated when they get updated, that is, there’s no schedule and no guarantee. If you need updates today you have at least two options:
> 
>  Option 1) Contribute your updates to the datasets.
> 
>  Option 2) Clone the datasets and update your own private or public copies yourself.

However, looking at their [project](https://github.com/openfootball) it does seem somewhat regular

**Comment by bgrnwd** [comment]
@devinpleuler Happy to open a PR if you'd like this added, otherwise I can close this issue
