### ISSUE TITLE
data_visualization.ipynb origin vs destination pass

### ISSUE THREAD

**Issue by Pakard1** [devinpleuler/analytics-handbook#8]
Hello,

How can we change this notebook (https://colab.research.google.com/github/devinpleuler/analytics-handbook/blob/master/notebooks/data_visualization.ipynb) to show the average location of both the origin and destination passes for every player instead of the average  of all the passes.

 a, b = sorted([passer_id, recipient_id]) # <-- Note:
Notice the Note where we sort the passer_id and recipient_id. This ensures that totals we accumulate represent both a -> b, and b -> a passes.

Here i wanted to differentiate between a->b and b-> positions in the field because i think it is interesting to analyze where the players received theirs passes and where did they received the passes from teammates

**Comment by devinpleuler** [comment]
This isn't an issue, so I'm going to close it.

The slice of code that you're looking at is actually for the weight of the connection between the players, not the positioning of the players. If you remove the sorting mechanism, you will have a two-directional relationship matrix -- which is just the first step of what you're looking for.

What you really need to change is the code in the next block of the notebook -- where you want to use the `end` coordinates of the pass as opposed to the raw `x` and `y` components that represent the starting position of the pass. If you dig into the JSON in the pass object, you can find these extra components.

**Comment by Pakard1** [comment]
Thank you for your response.

In the future, if i want to discuss anything related to a github repo,
where is the best place to do it?

I'm sorry for this noob question but i'm relatively new about github and
the environment.

Thank you again, i really enjoyed to explore your repo and im waiting for
updates.
